with-expecter: true

packages:
  todoshnik/internal/domains/task:
    config:
      dir: internal/domains/task/mocks
      outpkg: mocks
      filename: "{{.InterfaceName}}Mock.go"
      mockname: "{{.InterfaceName}}Mock"
    interfaces:
      Repository: {}
  todoshnik/cmd/api/app/task:
    config:
      dir: cmd/api/app/task/mocks
      outpkg: mocks
      filename: "{{.InterfaceName}}Mock.go"
      mockname: "{{.InterfaceName}}Mock"
    interfaces:
      UserGetter: {}
      TaskService: {}