// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	token "todoshnik/internal/domains/token"
	user "todoshnik/internal/domains/user"

	mock "github.com/stretchr/testify/mock"
)

// TokenServiceMock is an autogenerated mock type for the TokenService type
type TokenServiceMock struct {
	mock.Mock
}

type TokenServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenServiceMock) EXPECT() *TokenServiceMock_Expecter {
	return &TokenServiceMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, _a1, device
func (_m *TokenServiceMock) Add(ctx context.Context, _a1 *user.User, device token.DeviceType) (string, error) {
	ret := _m.Called(ctx, _a1, device)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User, token.DeviceType) (string, error)); ok {
		return rf(ctx, _a1, device)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.User, token.DeviceType) string); ok {
		r0 = rf(ctx, _a1, device)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.User, token.DeviceType) error); ok {
		r1 = rf(ctx, _a1, device)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenServiceMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type TokenServiceMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *user.User
//   - device token.DeviceType
func (_e *TokenServiceMock_Expecter) Add(ctx interface{}, _a1 interface{}, device interface{}) *TokenServiceMock_Add_Call {
	return &TokenServiceMock_Add_Call{Call: _e.mock.On("Add", ctx, _a1, device)}
}

func (_c *TokenServiceMock_Add_Call) Run(run func(ctx context.Context, _a1 *user.User, device token.DeviceType)) *TokenServiceMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.User), args[2].(token.DeviceType))
	})
	return _c
}

func (_c *TokenServiceMock_Add_Call) Return(_a0 string, _a1 error) *TokenServiceMock_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenServiceMock_Add_Call) RunAndReturn(run func(context.Context, *user.User, token.DeviceType) (string, error)) *TokenServiceMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, rawToken
func (_m *TokenServiceMock) Get(ctx context.Context, rawToken string) (*token.Token, error) {
	ret := _m.Called(ctx, rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *token.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*token.Token, error)); ok {
		return rf(ctx, rawToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *token.Token); ok {
		r0 = rf(ctx, rawToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rawToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenServiceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TokenServiceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - rawToken string
func (_e *TokenServiceMock_Expecter) Get(ctx interface{}, rawToken interface{}) *TokenServiceMock_Get_Call {
	return &TokenServiceMock_Get_Call{Call: _e.mock.On("Get", ctx, rawToken)}
}

func (_c *TokenServiceMock_Get_Call) Run(run func(ctx context.Context, rawToken string)) *TokenServiceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenServiceMock_Get_Call) Return(_a0 *token.Token, _a1 error) *TokenServiceMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenServiceMock_Get_Call) RunAndReturn(run func(context.Context, string) (*token.Token, error)) *TokenServiceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenServiceMock creates a new instance of TokenServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenServiceMock {
	mock := &TokenServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
