// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	user "todoshnik/internal/domains/user"

	mock "github.com/stretchr/testify/mock"
)

// UserServiceMock is an autogenerated mock type for the UserService type
type UserServiceMock struct {
	mock.Mock
}

type UserServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServiceMock) EXPECT() *UserServiceMock_Expecter {
	return &UserServiceMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, name, login, password
func (_m *UserServiceMock) Add(ctx context.Context, name string, login string, password string) (*user.User, error) {
	ret := _m.Called(ctx, name, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*user.User, error)); ok {
		return rf(ctx, name, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *user.User); ok {
		r0 = rf(ctx, name, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type UserServiceMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - login string
//   - password string
func (_e *UserServiceMock_Expecter) Add(ctx interface{}, name interface{}, login interface{}, password interface{}) *UserServiceMock_Add_Call {
	return &UserServiceMock_Add_Call{Call: _e.mock.On("Add", ctx, name, login, password)}
}

func (_c *UserServiceMock_Add_Call) Run(run func(ctx context.Context, name string, login string, password string)) *UserServiceMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *UserServiceMock_Add_Call) Return(_a0 *user.User, _a1 error) *UserServiceMock_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceMock_Add_Call) RunAndReturn(run func(context.Context, string, string, string) (*user.User, error)) *UserServiceMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddFromTg provides a mock function with given fields: ctx, name, telegramID
func (_m *UserServiceMock) AddFromTg(ctx context.Context, name string, telegramID int64) (*user.User, error) {
	ret := _m.Called(ctx, name, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for AddFromTg")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (*user.User, error)); ok {
		return rf(ctx, name, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) *user.User); ok {
		r0 = rf(ctx, name, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, name, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceMock_AddFromTg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFromTg'
type UserServiceMock_AddFromTg_Call struct {
	*mock.Call
}

// AddFromTg is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - telegramID int64
func (_e *UserServiceMock_Expecter) AddFromTg(ctx interface{}, name interface{}, telegramID interface{}) *UserServiceMock_AddFromTg_Call {
	return &UserServiceMock_AddFromTg_Call{Call: _e.mock.On("AddFromTg", ctx, name, telegramID)}
}

func (_c *UserServiceMock_AddFromTg_Call) Run(run func(ctx context.Context, name string, telegramID int64)) *UserServiceMock_AddFromTg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *UserServiceMock_AddFromTg_Call) Return(_a0 *user.User, _a1 error) *UserServiceMock_AddFromTg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceMock_AddFromTg_Call) RunAndReturn(run func(context.Context, string, int64) (*user.User, error)) *UserServiceMock_AddFromTg_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogin provides a mock function with given fields: ctx, login
func (_m *UserServiceMock) GetByLogin(ctx context.Context, login string) (*user.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceMock_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type UserServiceMock_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *UserServiceMock_Expecter) GetByLogin(ctx interface{}, login interface{}) *UserServiceMock_GetByLogin_Call {
	return &UserServiceMock_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login)}
}

func (_c *UserServiceMock_GetByLogin_Call) Run(run func(ctx context.Context, login string)) *UserServiceMock_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserServiceMock_GetByLogin_Call) Return(_a0 *user.User, _a1 error) *UserServiceMock_GetByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceMock_GetByLogin_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *UserServiceMock_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTgId provides a mock function with given fields: ctx, userTgID
func (_m *UserServiceMock) GetByTgId(ctx context.Context, userTgID int64) (*user.User, error) {
	ret := _m.Called(ctx, userTgID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTgId")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*user.User, error)); ok {
		return rf(ctx, userTgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *user.User); ok {
		r0 = rf(ctx, userTgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userTgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceMock_GetByTgId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTgId'
type UserServiceMock_GetByTgId_Call struct {
	*mock.Call
}

// GetByTgId is a helper method to define mock.On call
//   - ctx context.Context
//   - userTgID int64
func (_e *UserServiceMock_Expecter) GetByTgId(ctx interface{}, userTgID interface{}) *UserServiceMock_GetByTgId_Call {
	return &UserServiceMock_GetByTgId_Call{Call: _e.mock.On("GetByTgId", ctx, userTgID)}
}

func (_c *UserServiceMock_GetByTgId_Call) Run(run func(ctx context.Context, userTgID int64)) *UserServiceMock_GetByTgId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserServiceMock_GetByTgId_Call) Return(_a0 *user.User, _a1 error) *UserServiceMock_GetByTgId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceMock_GetByTgId_Call) RunAndReturn(run func(context.Context, int64) (*user.User, error)) *UserServiceMock_GetByTgId_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePassword provides a mock function with given fields: hash, password
func (_m *UserServiceMock) ValidatePassword(hash string, password string) (bool, error) {
	ret := _m.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePassword")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(hash, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hash, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceMock_ValidatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePassword'
type UserServiceMock_ValidatePassword_Call struct {
	*mock.Call
}

// ValidatePassword is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *UserServiceMock_Expecter) ValidatePassword(hash interface{}, password interface{}) *UserServiceMock_ValidatePassword_Call {
	return &UserServiceMock_ValidatePassword_Call{Call: _e.mock.On("ValidatePassword", hash, password)}
}

func (_c *UserServiceMock_ValidatePassword_Call) Run(run func(hash string, password string)) *UserServiceMock_ValidatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *UserServiceMock_ValidatePassword_Call) Return(_a0 bool, _a1 error) *UserServiceMock_ValidatePassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceMock_ValidatePassword_Call) RunAndReturn(run func(string, string) (bool, error)) *UserServiceMock_ValidatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserServiceMock creates a new instance of UserServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceMock {
	mock := &UserServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
