// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	user "todoshnik/internal/domains/user"

	mock "github.com/stretchr/testify/mock"
)

// UserGetterMock is an autogenerated mock type for the UserGetter type
type UserGetterMock struct {
	mock.Mock
}

type UserGetterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserGetterMock) EXPECT() *UserGetterMock_Expecter {
	return &UserGetterMock_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function with given fields: ctx, userID
func (_m *UserGetterMock) GetById(ctx context.Context, userID int) (*user.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*user.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *user.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetterMock_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type UserGetterMock_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *UserGetterMock_Expecter) GetById(ctx interface{}, userID interface{}) *UserGetterMock_GetById_Call {
	return &UserGetterMock_GetById_Call{Call: _e.mock.On("GetById", ctx, userID)}
}

func (_c *UserGetterMock_GetById_Call) Run(run func(ctx context.Context, userID int)) *UserGetterMock_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *UserGetterMock_GetById_Call) Return(_a0 *user.User, _a1 error) *UserGetterMock_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserGetterMock_GetById_Call) RunAndReturn(run func(context.Context, int) (*user.User, error)) *UserGetterMock_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserGetterMock creates a new instance of UserGetterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserGetterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserGetterMock {
	mock := &UserGetterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
