// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthorizerMock is an autogenerated mock type for the Authorizer type
type AuthorizerMock struct {
	mock.Mock
}

type AuthorizerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizerMock) EXPECT() *AuthorizerMock_Expecter {
	return &AuthorizerMock_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, token
func (_m *AuthorizerMock) Authorize(ctx context.Context, token string) (int, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizerMock_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type AuthorizerMock_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthorizerMock_Expecter) Authorize(ctx interface{}, token interface{}) *AuthorizerMock_Authorize_Call {
	return &AuthorizerMock_Authorize_Call{Call: _e.mock.On("Authorize", ctx, token)}
}

func (_c *AuthorizerMock_Authorize_Call) Run(run func(ctx context.Context, token string)) *AuthorizerMock_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthorizerMock_Authorize_Call) Return(_a0 int, _a1 error) *AuthorizerMock_Authorize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizerMock_Authorize_Call) RunAndReturn(run func(context.Context, string) (int, error)) *AuthorizerMock_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthorizerMock creates a new instance of AuthorizerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizerMock {
	mock := &AuthorizerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
