// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	user "todoshnik/internal/domains/user"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *RepositoryMock) Create(ctx context.Context, _a1 *user.User) (*user.User, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) (*user.User, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) *user.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.User) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *user.User
func (_e *RepositoryMock_Expecter) Create(ctx interface{}, _a1 interface{}) *RepositoryMock_Create_Call {
	return &RepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *RepositoryMock_Create_Call) Run(run func(ctx context.Context, _a1 *user.User)) *RepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.User))
	})
	return _c
}

func (_c *RepositoryMock_Create_Call) Return(_a0 *user.User, _a1 error) *RepositoryMock_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_Create_Call) RunAndReturn(run func(context.Context, *user.User) (*user.User, error)) *RepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, _a1
func (_m *RepositoryMock) Delete(ctx context.Context, _a1 *user.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *user.User
func (_e *RepositoryMock_Expecter) Delete(ctx interface{}, _a1 interface{}) *RepositoryMock_Delete_Call {
	return &RepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, _a1)}
}

func (_c *RepositoryMock_Delete_Call) Run(run func(ctx context.Context, _a1 *user.User)) *RepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.User))
	})
	return _c
}

func (_c *RepositoryMock_Delete_Call) Return(_a0 error) *RepositoryMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_Delete_Call) RunAndReturn(run func(context.Context, *user.User) error) *RepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *RepositoryMock) GetByID(ctx context.Context, id int) (*user.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*user.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *user.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RepositoryMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *RepositoryMock_Expecter) GetByID(ctx interface{}, id interface{}) *RepositoryMock_GetByID_Call {
	return &RepositoryMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *RepositoryMock_GetByID_Call) Run(run func(ctx context.Context, id int)) *RepositoryMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *RepositoryMock_GetByID_Call) Return(_a0 *user.User, _a1 error) *RepositoryMock_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetByID_Call) RunAndReturn(run func(context.Context, int) (*user.User, error)) *RepositoryMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogin provides a mock function with given fields: ctx, login
func (_m *RepositoryMock) GetByLogin(ctx context.Context, login string) (*user.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type RepositoryMock_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *RepositoryMock_Expecter) GetByLogin(ctx interface{}, login interface{}) *RepositoryMock_GetByLogin_Call {
	return &RepositoryMock_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login)}
}

func (_c *RepositoryMock_GetByLogin_Call) Run(run func(ctx context.Context, login string)) *RepositoryMock_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositoryMock_GetByLogin_Call) Return(_a0 *user.User, _a1 error) *RepositoryMock_GetByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetByLogin_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *RepositoryMock_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTgId provides a mock function with given fields: ctx, id
func (_m *RepositoryMock) GetByTgId(ctx context.Context, id int64) (*user.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByTgId")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*user.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *user.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetByTgId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTgId'
type RepositoryMock_GetByTgId_Call struct {
	*mock.Call
}

// GetByTgId is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *RepositoryMock_Expecter) GetByTgId(ctx interface{}, id interface{}) *RepositoryMock_GetByTgId_Call {
	return &RepositoryMock_GetByTgId_Call{Call: _e.mock.On("GetByTgId", ctx, id)}
}

func (_c *RepositoryMock_GetByTgId_Call) Run(run func(ctx context.Context, id int64)) *RepositoryMock_GetByTgId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *RepositoryMock_GetByTgId_Call) Return(_a0 *user.User, _a1 error) *RepositoryMock_GetByTgId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetByTgId_Call) RunAndReturn(run func(context.Context, int64) (*user.User, error)) *RepositoryMock_GetByTgId_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *RepositoryMock) List(ctx context.Context) ([]*user.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*user.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*user.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RepositoryMock_Expecter) List(ctx interface{}) *RepositoryMock_List_Call {
	return &RepositoryMock_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *RepositoryMock_List_Call) Run(run func(ctx context.Context)) *RepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RepositoryMock_List_Call) Return(_a0 []*user.User, _a1 error) *RepositoryMock_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_List_Call) RunAndReturn(run func(context.Context) ([]*user.User, error)) *RepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *RepositoryMock) Update(ctx context.Context, _a1 *user.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *user.User
func (_e *RepositoryMock_Expecter) Update(ctx interface{}, _a1 interface{}) *RepositoryMock_Update_Call {
	return &RepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *RepositoryMock_Update_Call) Run(run func(ctx context.Context, _a1 *user.User)) *RepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.User))
	})
	return _c
}

func (_c *RepositoryMock_Update_Call) Return(_a0 error) *RepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_Update_Call) RunAndReturn(run func(context.Context, *user.User) error) *RepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
