// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	task "todoshnik/internal/domains/task"
	identity "todoshnik/internal/infrastructure/identity"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *RepositoryMock) Create(ctx context.Context, _a1 *task.Task) (*task.Task, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) (*task.Task, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) *task.Task); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *task.Task) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *task.Task
func (_e *RepositoryMock_Expecter) Create(ctx interface{}, _a1 interface{}) *RepositoryMock_Create_Call {
	return &RepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *RepositoryMock_Create_Call) Run(run func(ctx context.Context, _a1 *task.Task)) *RepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.Task))
	})
	return _c
}

func (_c *RepositoryMock_Create_Call) Return(_a0 *task.Task, _a1 error) *RepositoryMock_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_Create_Call) RunAndReturn(run func(context.Context, *task.Task) (*task.Task, error)) *RepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, _a1
func (_m *RepositoryMock) Delete(ctx context.Context, _a1 *task.Task) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *task.Task
func (_e *RepositoryMock_Expecter) Delete(ctx interface{}, _a1 interface{}) *RepositoryMock_Delete_Call {
	return &RepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, _a1)}
}

func (_c *RepositoryMock_Delete_Call) Run(run func(ctx context.Context, _a1 *task.Task)) *RepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.Task))
	})
	return _c
}

func (_c *RepositoryMock_Delete_Call) Return(_a0 error) *RepositoryMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_Delete_Call) RunAndReturn(run func(context.Context, *task.Task) error) *RepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, scope
func (_m *RepositoryMock) GetByID(ctx context.Context, id int, scope identity.AccessScope) (*task.Task, error) {
	ret := _m.Called(ctx, id, scope)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, identity.AccessScope) (*task.Task, error)); ok {
		return rf(ctx, id, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, identity.AccessScope) *task.Task); ok {
		r0 = rf(ctx, id, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, identity.AccessScope) error); ok {
		r1 = rf(ctx, id, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RepositoryMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - scope identity.AccessScope
func (_e *RepositoryMock_Expecter) GetByID(ctx interface{}, id interface{}, scope interface{}) *RepositoryMock_GetByID_Call {
	return &RepositoryMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, scope)}
}

func (_c *RepositoryMock_GetByID_Call) Run(run func(ctx context.Context, id int, scope identity.AccessScope)) *RepositoryMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(identity.AccessScope))
	})
	return _c
}

func (_c *RepositoryMock_GetByID_Call) Return(_a0 *task.Task, _a1 error) *RepositoryMock_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_GetByID_Call) RunAndReturn(run func(context.Context, int, identity.AccessScope) (*task.Task, error)) *RepositoryMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *RepositoryMock) List(ctx context.Context, filter task.TaskFilter) ([]*task.Task, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, task.TaskFilter) ([]*task.Task, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, task.TaskFilter) []*task.Task); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, task.TaskFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter task.TaskFilter
func (_e *RepositoryMock_Expecter) List(ctx interface{}, filter interface{}) *RepositoryMock_List_Call {
	return &RepositoryMock_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *RepositoryMock_List_Call) Run(run func(ctx context.Context, filter task.TaskFilter)) *RepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.TaskFilter))
	})
	return _c
}

func (_c *RepositoryMock_List_Call) Return(_a0 []*task.Task, _a1 error) *RepositoryMock_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryMock_List_Call) RunAndReturn(run func(context.Context, task.TaskFilter) ([]*task.Task, error)) *RepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *RepositoryMock) Update(ctx context.Context, _a1 *task.Task) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *task.Task) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *task.Task
func (_e *RepositoryMock_Expecter) Update(ctx interface{}, _a1 interface{}) *RepositoryMock_Update_Call {
	return &RepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *RepositoryMock_Update_Call) Run(run func(ctx context.Context, _a1 *task.Task)) *RepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*task.Task))
	})
	return _c
}

func (_c *RepositoryMock_Update_Call) Return(_a0 error) *RepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryMock_Update_Call) RunAndReturn(run func(context.Context, *task.Task) error) *RepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
