// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	task "todoshnik/internal/domains/task"
	identity "todoshnik/internal/infrastructure/identity"

	mock "github.com/stretchr/testify/mock"
)

// TaskServiceMock is an autogenerated mock type for the TaskService type
type TaskServiceMock struct {
	mock.Mock
}

type TaskServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskServiceMock) EXPECT() *TaskServiceMock_Expecter {
	return &TaskServiceMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, title, taskID
func (_m *TaskServiceMock) Add(ctx context.Context, title string, taskID int) (*task.Task, error) {
	ret := _m.Called(ctx, title, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*task.Task, error)); ok {
		return rf(ctx, title, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *task.Task); ok {
		r0 = rf(ctx, title, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, title, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type TaskServiceMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - taskID int
func (_e *TaskServiceMock_Expecter) Add(ctx interface{}, title interface{}, taskID interface{}) *TaskServiceMock_Add_Call {
	return &TaskServiceMock_Add_Call{Call: _e.mock.On("Add", ctx, title, taskID)}
}

func (_c *TaskServiceMock_Add_Call) Run(run func(ctx context.Context, title string, taskID int)) *TaskServiceMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *TaskServiceMock_Add_Call) Return(_a0 *task.Task, _a1 error) *TaskServiceMock_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_Add_Call) RunAndReturn(run func(context.Context, string, int) (*task.Task, error)) *TaskServiceMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, taskID, scope
func (_m *TaskServiceMock) Delete(ctx context.Context, taskID int, scope identity.AccessScope) error {
	ret := _m.Called(ctx, taskID, scope)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, identity.AccessScope) error); ok {
		r0 = rf(ctx, taskID, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TaskServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int
//   - scope identity.AccessScope
func (_e *TaskServiceMock_Expecter) Delete(ctx interface{}, taskID interface{}, scope interface{}) *TaskServiceMock_Delete_Call {
	return &TaskServiceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, taskID, scope)}
}

func (_c *TaskServiceMock_Delete_Call) Run(run func(ctx context.Context, taskID int, scope identity.AccessScope)) *TaskServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(identity.AccessScope))
	})
	return _c
}

func (_c *TaskServiceMock_Delete_Call) Return(_a0 error) *TaskServiceMock_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskServiceMock_Delete_Call) RunAndReturn(run func(context.Context, int, identity.AccessScope) error) *TaskServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *TaskServiceMock) List(ctx context.Context, filter task.TaskFilter) ([]*task.Task, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, task.TaskFilter) ([]*task.Task, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, task.TaskFilter) []*task.Task); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, task.TaskFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TaskServiceMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter task.TaskFilter
func (_e *TaskServiceMock_Expecter) List(ctx interface{}, filter interface{}) *TaskServiceMock_List_Call {
	return &TaskServiceMock_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *TaskServiceMock_List_Call) Run(run func(ctx context.Context, filter task.TaskFilter)) *TaskServiceMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(task.TaskFilter))
	})
	return _c
}

func (_c *TaskServiceMock_List_Call) Return(_a0 []*task.Task, _a1 error) *TaskServiceMock_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_List_Call) RunAndReturn(run func(context.Context, task.TaskFilter) ([]*task.Task, error)) *TaskServiceMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDone provides a mock function with given fields: ctx, taskID, scope
func (_m *TaskServiceMock) MarkDone(ctx context.Context, taskID int, scope identity.AccessScope) (*task.Task, error) {
	ret := _m.Called(ctx, taskID, scope)

	if len(ret) == 0 {
		panic("no return value specified for MarkDone")
	}

	var r0 *task.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, identity.AccessScope) (*task.Task, error)); ok {
		return rf(ctx, taskID, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, identity.AccessScope) *task.Task); ok {
		r0 = rf(ctx, taskID, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, identity.AccessScope) error); ok {
		r1 = rf(ctx, taskID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskServiceMock_MarkDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDone'
type TaskServiceMock_MarkDone_Call struct {
	*mock.Call
}

// MarkDone is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int
//   - scope identity.AccessScope
func (_e *TaskServiceMock_Expecter) MarkDone(ctx interface{}, taskID interface{}, scope interface{}) *TaskServiceMock_MarkDone_Call {
	return &TaskServiceMock_MarkDone_Call{Call: _e.mock.On("MarkDone", ctx, taskID, scope)}
}

func (_c *TaskServiceMock_MarkDone_Call) Run(run func(ctx context.Context, taskID int, scope identity.AccessScope)) *TaskServiceMock_MarkDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(identity.AccessScope))
	})
	return _c
}

func (_c *TaskServiceMock_MarkDone_Call) Return(_a0 *task.Task, _a1 error) *TaskServiceMock_MarkDone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskServiceMock_MarkDone_Call) RunAndReturn(run func(context.Context, int, identity.AccessScope) (*task.Task, error)) *TaskServiceMock_MarkDone_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskServiceMock creates a new instance of TaskServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskServiceMock {
	mock := &TaskServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
