// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TokenServiceMock is an autogenerated mock type for the TokenService type
type TokenServiceMock struct {
	mock.Mock
}

type TokenServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenServiceMock) EXPECT() *TokenServiceMock_Expecter {
	return &TokenServiceMock_Expecter{mock: &_m.Mock}
}

// ClearExpiredTokens provides a mock function with given fields: ctx
func (_m *TokenServiceMock) ClearExpiredTokens(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearExpiredTokens")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenServiceMock_ClearExpiredTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearExpiredTokens'
type TokenServiceMock_ClearExpiredTokens_Call struct {
	*mock.Call
}

// ClearExpiredTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TokenServiceMock_Expecter) ClearExpiredTokens(ctx interface{}) *TokenServiceMock_ClearExpiredTokens_Call {
	return &TokenServiceMock_ClearExpiredTokens_Call{Call: _e.mock.On("ClearExpiredTokens", ctx)}
}

func (_c *TokenServiceMock_ClearExpiredTokens_Call) Run(run func(ctx context.Context)) *TokenServiceMock_ClearExpiredTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TokenServiceMock_ClearExpiredTokens_Call) Return(_a0 int, _a1 error) *TokenServiceMock_ClearExpiredTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenServiceMock_ClearExpiredTokens_Call) RunAndReturn(run func(context.Context) (int, error)) *TokenServiceMock_ClearExpiredTokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenServiceMock creates a new instance of TokenServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenServiceMock {
	mock := &TokenServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
